export const data = {
  products: [
    {
      name: "heavy pot",
      slug: "heavy-pot",
      category: "Cook-ware",
      image: "/images/pic1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 0.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "pan",
      slug: "heavy-pan",
      category: "cook ware",
      image: "/images/pic2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Plastic Container",
      slug: "plastic-container",
      category: "Food-storage",
      image: "/images/pic3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "apron",
      slug: "quality-apron",
      category: "kitchen-linens",
      image: "/images/pic4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Skillet",
      slug: "heavy-skillet",
      category: "cooke-ware",
      image: "/images/pic5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "roasting pans",
      slug: "roasting-pans",
      category: "cook-ware",
      image: "/images/pic6.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "muffin pans",
      slug: "muffin-pans",
      category: "cook-ware",
      image: "/images/pic7.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "spice racks",
      slug: "spice-racks",
      category: "food-storage and organizations",
      image: "/images/pic8.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Table Clothes",
      slug: "table-clothes",
      category: "kitchen Linens",
      image: "/images/pic9.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "roasting-pans",
      slug: "adidas-fit-pant",
      category: "cook- ware",
      image: "/images/pic10.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "dish towels",
      slug: "dish-towels",
      category: "kitchen Linens",
      image: "/images/pic11.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "lunch boxes",
      slug: "lunch-boxes",
      category: "food-storage",
      image: "/images/pic12.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
