import bcrypt from 'bcryptjs';

export const data = {
  users: [
    {
      name: 'Gashaw',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12456'),
      isAdmin: true,
    },
    {
      name: 'Mimi',
      email: 'admin@example2.com',
      password: bcrypt.hashSync('126789'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Heavy pot',
      slug: 'heavy-pot',
      category: 'Cook ware',
      image: '/images/pic1.jpg',
      price: 2,
      countInStock: 0,
      brand: 'Brand 1',
      rating: 0.5,
      numReviews: 10,
      description: 'high quality pot',
    },
    {
      name: 'Pan',
      slug: 'heavy-pan',
      category: 'cook ware',
      image: '/images/pic2.jpg',
      price: 29.99,
      countInStock: 20,
      brand: 'Brand 2',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality pan',
    },
    {
      name: 'Plastic Container',
      slug: 'plastic-container',
      category: 'Food-storage',
      image: '/images/pic3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Brand 3',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality plastic container',
    },
    {
      name: 'Apron',
      slug: 'quality-apron',
      category: 'kitchen-linens',
      image: '/images/pic4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Brand 4',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Skillet',
      slug: 'heavy-skillet',
      category: 'cooke-ware',
      image: '/images/pic5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Brand 2',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality skillet',
    },
    {
      name: 'Roasting Pans',
      slug: 'roasting-pans',
      category: 'cook-ware',
      image: '/images/pic6.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Brand 2',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality roasting pans',
    },
    {
      name: 'Muffin Pans',
      slug: 'muffin-pans',
      category: 'cook ware',
      image: '/images/pic7.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Brand 4',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Spice racks',
      slug: 'spice-racks',
      category: 'food-storage and organizations',
      image: '/images/pic8.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Table Clothes',
      slug: 'table-clothes',
      category: 'kitchen Linens',
      image: '/images/pic9.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'roasting-pans',
      slug: 'adidas-fit-pant',
      category: 'cook- ware',
      image: '/images/pic10.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'dish towels',
      slug: 'dish-towels',
      category: 'kitchen Linens',
      image: '/images/pic11.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'lunch boxes',
      slug: 'lunch-boxes',
      category: 'food-storage',
      image: '/images/pic12.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
