export const data = {
  products: [
    {
      _id: 1,
      name: 'Plastic Container',
      slug: 'plastic-container',
      category: 'food storage',
      image: '/images/pic9.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Brand 1',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 2,
      name: 'Table-Clothing',
      slug: 'table-clothing ',
      category: 'cook ware',
      image: '/images/pic10.jpg',
      countInStock: 5,
      brand: 'Brand 4',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 3,
      name: 'Dish-Towel',
      slug: 'dish-towel',
      category: 'cook ware',
      image: '/images/pic12.jpg',
      price: 201,
      countInStock: 5,
      brand: 'Brand 4',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 4,
      name: 'Roasting Pan',
      slug: 'roasting-pan',
      category: 'cook ware',
      image: '/images/pic6.jpg',
      price: 45,
      countInStock: 5,
      brand: 'Brand 2',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 5,
      name: 'Spice Rock',
      slug: 'spice-rack',
      category: 'cook ware',
      image: '/images/pic7.jpg',
      price: 55,
      countInStock: 5,
      brand: 'Brand 4',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 6,
      name: 'Skillet',
      slug: 'heavy-skillet',
      category: 'cook-ware',
      image: '/images/pic5.jpg',
      price: 32,
      countInStock: 5,
      brand: 'Brand 2',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 7,
      name: 'Lunch Box',
      slug: 'lunch-box',
      category: 'food storage',
      image: '/images/pic8.jpg',
      price: 64,
      countInStock: 5,
      brand: 'Brand 1',
      rating: 5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      _id: 8,
      name: 'Apron',
      slug: 'high-apron',
      category: 'food-storage and organizations',
      image: '/images/pic11.jpg',
      price: 70,
      countInStock: 5,
      brand: 'Brand 3',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
