// import prod1 from "../src/images/pic1.jpg";
// import prod2 from "../src/images/pic2.jpg";
// import prod3 from "../src/images/pic3.jpg";
// import prod4 from "../src/images/pic4.jpg";
// import prod5 from "../src/images/pic5.jpg";
// import prod6 from "../src/images/pic6.jpg";
// import prod7 from "../src/images/pic7.jpg";
// import prod8 from "../src/images/pic8.jpg";
// import prod9 from "../src/images/pic9.jpg";
// import prod10 from "../src/images/pic10.jpg";
// import prod11 from "../src/images/pic11.jpg";
// import prod12 from "../src/images/pic12.jpg";

export const data = {
  products: [
    {
      _id: 1,
      name: "heavy pot",
      slug: "heavy-pot",
      category: "Cook-ware",
      image: "/images/pic1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: 2,
      name: "pan",
      slug: "heavy pan ",
      category: "cook ware",
      image: "/images/pic2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 3,
      name: "Plasti Container",
      slug: "plastic-container",
      category: "Food-storage",
      image: "/images/pic3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: 4,
      name: "apron",
      slug: "quality-apron",
      category: "kitchen-linens",
      image: "/images/pic4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 5,
      name: "Skillet",
      slug: "heavy-skillet",
      category: "cooke-ware",
      image: "/images/pic5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 6,
      name: "roasting pans",
      slug: "roasting-pans",
      category: "cook-ware",
      image: "/images/pic6.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 7,
      name: "muffin pans",
      slug: "muffin-pans",
      category: "cook-ware",
      image: "/images/pic7.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 8,
      name: "spice racks",
      slug: "spice-racks",
      category: "food-storage and organizations",
      image: "/images/pic8.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 9,
      name: "Table Clothes",
      slug: "table-clothes",
      category: "kitchen Linens",
      image: "/images/pic9.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 10,
      name: "roasting-pans",
      slug: "adidas-fit-pant",
      category: "cook- ware",
      image: "/images/pic10.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 11,
      name: "dish towels",
      slug: "dish-towels",
      category: "kitchen Linens",
      image: "/images/pic11.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 12,
      name: "lunch boxes",
      slug: "lunch-boxes",
      category: "food-storage",
      image: "/images/pic12.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
